# Generated by Django 3.2.11 on 2022-01-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('vegetarian', models.CharField(blank=True, max_length=1, null=True)),
                ('max_calories', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
