# Generated by Django 3.2.11 on 2022-01-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_users_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
