# Generated by Django 3.2.11 on 2022-01-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
