# Generated by Django 3.2.11 on 2022-01-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('vote_count', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=13, max_digits=14)),
                ('description', models.TextField()),
                ('course', models.TextField()),
                ('diet', models.TextField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
