# Generated by Django 3.2.11 on 2022-01-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaloriesBurnedDuringExercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriesburnedduringexercise',
            name='exercise',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
    ]
