# Generated by Django 3.2.11 on 2022-01-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaloriesBurnedDuringExercise', '0002_caloriesburnedduringexercise_exercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaloriesBurnedDuringExercise',
        ),
    ]
