# Generated by Django 3.2.11 on 2022-01-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CaloriesBurnedDuringExercise', '0003_delete_caloriesburnedduringexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='caloriesBurnedDuringExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(default='DEFAULT', max_length=255)),
                ('lb130', models.IntegerField()),
                ('lb155', models.IntegerField()),
                ('lb180', models.IntegerField()),
                ('lb205', models.IntegerField()),
                ('calories_per_kg', models.DecimalField(decimal_places=14, max_digits=15)),
            ],
        ),
    ]
