# Generated by Django 3.2.11 on 2022-01-27 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaloriesBurnedDuringExercise', '0004_caloriesburnedduringexercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloriesburnedduringexercise',
            old_name='lb155',
            new_name='lb150',
        ),
    ]
