# Generated by Django 3.2.11 on 2022-01-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaloriesBurnedDuringExercise', '0005_rename_lb155_caloriesburnedduringexercise_lb150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriesburnedduringexercise',
            name='exercise',
            field=models.TextField(),
        ),
    ]
